/*
 * Copyright (c) Haulmont 2025. All Rights Reserved.
 * Use is subject to license terms.
 */

plugins {
    id 'java'
    id 'maven-publish'
}

group = 'io.flowset.ui'

repositories {
    mavenCentral()
    maven {
        url = 'https://global.repo.jmix.io/repository/public'
    }
}

dependencies {
    implementation 'io.jmix.flowui:jmix-flowui-themes:3.0.1'
}

java {
    withJavadocJar()
    withSourcesJar()
}

publishing {
    if (rootProject.hasProperty('flowsetUploadUrl')) {
        repositories {
            maven {
                url = rootProject['flowsetUploadUrl']
                credentials {
                    username = rootProject['flowsetUploadUser']
                    password = rootProject['flowsetUploadPassword']
                }
                allowInsecureProtocol = true
            }
        }
    }

    publications {
        maven(MavenPublication) {
            artifactId = 'flowset-theme'
            from components.java
        }
    }
}
